### ISSUE TITLE
NPM Release

### ISSUE THREAD

**Issue by Ehesp** [Schachte/cloudflare-google-auth#3]
Hello - could you create a new NPM release with the changes which were last merged? I'm having to use `patch-package` in a few projects with the edits at the moment.

Thank you.

**Comment by Schachte** [comment]
Can you just:
`npm install git+https://github.com/schachte/cloudflare-google-auth.git` ?

**Comment by Schachte** [comment]
Apologies for the delay, I've gone ahead and published a v2.0.0 release for this. Thanks for the changes:
https://www.npmjs.com/package/cloudflare-workers-and-google-oauth
